### ISSUE TITLE
IP not permisstion. why can i create and submit order through api but can't get status of order through above api?

### ISSUE THREAD

**Issue by khanhtran94** [binance/binance-futures-connector-java#14] opened 2023-04-10 15:03 UTC
code get status
```
        String infoStateOrder = umFuturesClient.account().queryOrder(parametersGetOrder);
```
I have granted enough ip

**Comment by aisling-2** [comment] 2024-01-09 18:11
Since this issue has been open for a while, we're not sure what's the current status.
However, using `src/test/java/examples/um_futures/account/QueryOrder.java` with the current connector version `3.0.3` and Futures Testnet URL and API keys, we can't reproduce the stated issue.

Given the reasons above, we're closing the issue. However, if someone run into a similar issue, please open a new issue with a more detailed description so that we can get more context: the used steps, expected result, what got instead and the exact returned error message.

**Closed by aisling-2** 2024-01-09 18:11 UTC
